### PR TITLE
Take default value of CheckboxColumn into account while adding a new column in the edit form

### PR DESCRIPTION
**Pull request by gbastien**
Hi @mauritsvanrees 

sorry I forgot to push this change together with previous one...

Can you have a look when you have time?  It will "check" the box depending on CheckboxColumn default while adding a new row...

If you are about to add some other feature, we can wait for a release to avoid several releases same day ;-)

Thank you!

Gauthier

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Looks okay. But can't the default also be `True` instead of `1`? Maybe examples currently use `1`, but I guess it can be any `True` value.

**Comment by gbastien** [comment]
Always used it with '1' as checked and '' as not checked, moreover looking here :

https://github.com/collective/Products.DataGridField/blob/master/Products/DataGridField/skins/DataGridWidget/datagrid_checkbox_cell.pt#L22

It seems that '1' is taken as only possible 'checked' value, what do you think?

Gauthier

**Comment by mauritsvanrees** [comment]
Strange: I tried adding `default=True` to an example checkbox column, and changed your code to a simple boolean check `column_definition.getDefault(here)` but that did not work. I don't know why. But with `default='1'` your code works. Seems a bit strange to me, but it fits the rest of the code.
Thanks, I will merge.

**Comment by mauritsvanrees** [comment]
1.9.4 released.

**Comment by gbastien** [comment]
Thx!

**Pull request merged**
